
* What is this?
A [[https://guix.gnu.org/][Guix]] channel.

* What's in this channel?
It started as a channel to have the latest git-tip of Luajit and the latest git-tip of the Awesome window manager (and a definition for AwesomeWM using Luajit (originally based on [[https://git.sr.ht/~shtwzrd/sht-channel][shtwzrd's Guix channel]], which hasn't been updated in a while)) rather than plain Lua, both Guix's current Luajit (=awesome-next-luajit=) and using the tip of the Luajit git repo (=awesome-next-luajit-tip=)).

Thus originally "awesomejit". (So, perhaps, a "just in time" channel for "awesome" packages.)

But there's some other things in it now, random miscellany of what I need, so "jitterymisc". Includes things like custom builds of native-comp Emacs with lucid/athena toolkit.

* To use this channel
Add to your =channels.scm= file (maybe in =~/.config/guix/=):

#+begin_src scheme
(cons* (channel (name other-channel... ....
       (channel
        (name 'jitterymisc)
        (url "https://github.com/emacsomancer/guix-jittery-miscellany")
        (branch "main"))
       %default-channels)
#+end_src

(Where =(channel (name other-channel... ....= represents other channels you may have added.)

And then execute =guix pull= and then proceed however you add packages to your Guix.
